/**
 * seed_flashcards.js — Ingest flashcards generated by Gemini into study_materials.
 *
 * Usage:
 *   node seed_flashcards.js ./flashcards_data/gate_ee_flashcards.json
 *
 * JSON format expected:
 * {
 *   "flashcard_materials": [
 *     {
 *       "exam_name": "GATE EE",
 *       "subject_name": "Engineering Mathematics",
 *       "topic_name": "Linear Algebra",
 *       "title": "High-Yield Linear Algebra",
 *       "cards": [
 *         { "front": "Q1", "back": "A1" }
 *       ]
 *     }
 *   ]
 * }
 */

const { Pool } = require('pg');
const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../../.env') });

function healLatexEscapes(raw) {
    let result = '';
    let inString = false;
    let i = 0;
    while (i < raw.length) {
        const ch = raw[i];
        if (!inString) {
            if (ch === '"') inString = true;
            result += ch;
            i++;
        } else {
            if (ch === '"') {
                inString = false;
                result += ch;
                i++;
            } else if (ch === '\\') {
                const next = raw[i + 1];
                if (next === undefined) {
                    result += ch;
                    i++;
                } else if (next === '\\') {
                    result += '\\\\';
                    i += 2;
                } else if (next === '"') {
                    result += '\\"';
                    i += 2;
                } else if (next === '/') {
                    result += '\\/';
                    i += 2;
                } else if (next === 'u' && /^[0-9a-fA-F]{4}/.test(raw.slice(i + 2, i + 6))) {
                    result += raw.slice(i, i + 6);
                    i += 6;
                } else {
                    result += '\\\\' + next;
                    i += 2;
                }
            } else {
                result += ch;
                i++;
            }
        }
    }
    return result;
}

function parseAIJson(val) {
    if (!val) return null;
    let raw = val.replace(/^```[a-z]*\s*/gim, '').replace(/```\s*$/gim, '').trim();
    let healed = healLatexEscapes(raw);
    try {
        return JSON.parse(healed);
    } catch (err) {
        return JSON.parse(raw);
    }
}

const pool = new Pool({ connectionString: process.env.DATABASE_URL });

async function seedFlashcards(filePath) {
    const client = await pool.connect();

    try {
        const raw = fs.readFileSync(path.resolve(filePath), 'utf8');
        const data = parseAIJson(raw);

        if (!data.flashcard_materials || !Array.isArray(data.flashcard_materials)) {
            throw new Error('JSON must have "flashcard_materials" array.');
        }

        console.log(`\nSeeding Flashcards from: ${filePath}`);
        console.log(`Found ${data.flashcard_materials.length} flashcard decks to process.`);

        await client.query('BEGIN');

        let inserted = 0;
        let skipped = 0;

        for (const deck of data.flashcard_materials) {
            console.log(`\nProcessing: ${deck.title} for ${deck.exam_name} -> ${deck.topic_name}`);
            
            // 1. Find Exam mapping
            const examRes = await client.query('SELECT id FROM exams WHERE name = $1 LIMIT 1', [deck.exam_name]);
            if (examRes.rows.length === 0) {
                console.error(`  ❌ Skipping: Exam not found ("${deck.exam_name}")`);
                skipped++;
                continue;
            }
            const examId = examRes.rows[0].id;

            // 2. Find Subject mapping
            const subjRes = await client.query(
                `SELECT id FROM exam_subjects 
                 WHERE exam_id = $1 
                 AND (LOWER(TRIM(name)) = LOWER(TRIM($2)) OR name ILIKE $3) 
                 LIMIT 1`,
                [examId, deck.subject_name, '%' + deck.subject_name.trim() + '%']
            );
            if (subjRes.rows.length === 0) {
                console.error(`  ❌ Skipping: Subject not found ("${deck.subject_name}")`);
                skipped++;
                continue;
            }
            const subjectId = subjRes.rows[0].id;

            // 3. Find Topic mapping
            // Topic names might have colons and descriptions, so we do a partial match or exact match.
            // Using ILIKE to handle slight discrepancies from AI generation.
            // Improved matching: exact, then start of string, then partial
            const topicCleaned = deck.topic_name.trim();
            const topicNoColon = topicCleaned.split(':')[0].trim();

            const topicRes = await client.query(
                `SELECT id FROM exam_topics 
                 WHERE subject_id = $1 
                 AND (
                    LOWER(TRIM(name)) = LOWER($2) 
                    OR LOWER(TRIM(name)) = LOWER($3)
                    OR name ILIKE $4
                    OR name ILIKE $5
                 ) 
                 LIMIT 1`,
                [subjectId, topicCleaned, topicNoColon, topicCleaned + '%', topicNoColon + '%']
            );
            
            if (topicRes.rows.length === 0) {
                console.error(`  ❌ Skipping: Topic not found ("${deck.topic_name}") for Subject "${deck.subject_name}"`);
                skipped++;
                continue;
            }
            const topicId = topicRes.rows[0].id;

            // 4. Insert or Update into study_materials
            // We use content_type = 'flashcard_json'
            // We can delete any existing one for this exact title/topic just to be idempotent.
            await client.query(
                `DELETE FROM study_materials 
                 WHERE exam_id = $1 AND topic_id = $2 AND content_type = 'flashcard_json' AND title = $3`,
                [examId, topicId, deck.title]
            );

            await client.query(
                `INSERT INTO study_materials 
                 (exam_id, subject_id, topic_id, title, content_type, content, is_published, source)
                 VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`,
                [
                    examId, 
                    subjectId, 
                    topicId, 
                    deck.title || 'Flashcard Deck', 
                    'flashcard_json', 
                    JSON.stringify(deck.cards), 
                    true,
                    'system'
                ]
            );

            console.log(`  ✅ Inserted ${deck.cards.length} cards.`);
            inserted++;
        }

        await client.query('COMMIT');
        console.log(`\n🎉 Seeding Complete!`);
        console.log(`✅ Inserted/Updated: ${inserted} decks.`);
        console.log(`⏭️  Skipped (Mapping failed): ${skipped} decks.`);

    } catch (err) {
        await client.query('ROLLBACK');
        console.error('\n❌ Seed failed:', err.message);
    } finally {
        client.release();
        await pool.end();
    }
}

// CLI
const args = process.argv.slice(2);
const filePath = args[0];

if (!filePath) {
    console.log('Usage: node seed_flashcards.js <path-to-json>');
    console.log('Example: node seed_flashcards.js ./flashcard_data/gate_ae_flashcards.json');
    process.exit(1);
}

seedFlashcards(filePath);
